poss_move(pawn, 10).
poss_move(pawn, 11).
poss_move(pawn, 20).
poss_move(pawn, -9).
poss_move(rook, 1).
poss_move(rook, 10).
poss_move(rook, -1).
poss_move(rook, -10).
poss_move(knight, 8).
poss_move(knight, -21).
poss_move(knight, 12).
poss_move(knight, -19).
poss_move(knight, 19).
poss_move(knight, -12).
poss_move(knight, 21).
poss_move(knight, -8).
poss_move(bishop, 9).
poss_move(bishop, 11).
poss_move(bishop, -11).
poss_move(bishop, -9).
poss_move(queen, 1).
poss_move(queen, 9).
poss_move(queen, 10).
poss_move(queen, 11).
poss_move(queen, -11).
poss_move(queen, -10).
poss_move(queen, -9).
poss_move(queen, -1).
poss_move(king, 1).
poss_move(king, 9).
poss_move(king, 10).
poss_move(king, -11).
poss_move(king, -10).
poss_move(king, -9).
